# items-jwt.http
### auth login

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "domonkitti",
    "password": "1234"
}

###
@authToken = {{login.response.body.access_token}}


### find all
GET http://localhost:3000/items
Authorization: Bearer {{authToken}}

### dit
GET http://localhost:3000/items/edit/edit
Authorization: Bearer {{authToken}}


### approve
PATCH http://localhost:3000/items/3/approve
Authorization: Bearer {{authToken}}


###
### Admin Zone
###
# @name loginAdmin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "a1001",
    "password": "changeit"
}

###
@authTokenAdmin = {{loginAdmin.response.body.access_token}}

### Admin approve
PATCH http://localhost:3000/items/3/approve
Authorization: Bearer {{authTokenAdmin}}



###
### Manager Zone
###
# @name loginManager
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "manage01",
    "password": "changeit"
}

###
@authTokenManager = {{loginManager.response.body.access_token}}

### Manager approve
PATCH http://localhost:3000/items/3/approve
Authorization: Bearer {{authTokenManager}}